[package]
name = "ethsbell-rewrite"
version = "0.2.4"
authors = ["Willow <willow.ch@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
rocket_contrib = {version = "0.4.7", features = ["json"]}
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"
chrono = {version = "0.4.19", features = ["serde"]}
reqwest = {version = "0.11.3", features = ["blocking"]}
serde_regex = "1.1.0"
regex = "1.4.6"
urlencoding = "1.1.1"
thiserror = "1.0.24"

[lib]
path = "src/main.rs"

[profile.release]
lto = "fat"
codegen-units = 1

[profile.release.package."*"]
codegen-units = 1
